name: example
description: Example of the object_3d library.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  object_3d:
    path: ../

flutter:
  assets:
    - assets/file.obj