include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # workaround for https://github.com/dart-lang/sdk/issues/42910
    - 'example/**'

linter:
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    always_specify_types: true
    void_checks: true
    use_raw_strings: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    unnecessary_null_aware_assignments: true
    unnecessary_new: true
    unnecessary_late: true
    unnecessary_lambdas: true
    unnecessary_brace_in_string_interps: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    lines_longer_than_80_chars: true
    avoid_setters_without_getters: true
    avoid_return_types_on_setters: true
    annotate_overrides: true
    always_put_required_named_parameters_first: true