name: object_3d
description: Simple Flutter renderer for .obj files with options to render custom colors.
version: 0.0.1
homepage: https://github.com/arnovanliere/object_3d

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.1
